import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { open } from "@tauri-apps/api/shell";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>T3 Tauri App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[conic-gradient(at_bottom,_var(--tw-gradient-stops))] from-purple-800 via-purple-700 to-blue-700">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Tauri <span className="text-purple-400">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <button
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/20 p-10 text-white hover:bg-white/30"
              onClick={() => {
                open("https://tauri.app");
              }}
            >
              <h3 className="text-2xl font-bold">Tauri Docs →</h3>
              <div className="text-justify text-lg">
                Learn more about Tauri — Build smaller, faster, and more secure
                desktop applications with a web frontend.
              </div>
            </button>
            <button
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/20 p-10 text-white hover:bg-white/30"
              onClick={() => {
                open("https://create.t3.gg/en/introduction");
              }}
            >
              <h3 className="text-2xl font-bold">T3 Docs →</h3>
              <div className="text-justify text-lg">
                Learn more about Create T3 App — The best way to start a
                full-stack, typesafe Next.js app.
              </div>
            </button>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl font-semibold text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white px-10 py-3 text-xl font-bold text-black no-underline transition hover:bg-white/75"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
